export const CINEMA_DETAILS_PAGE_REQUEST = "movieDetailsReducer/CINEMA_DETAILS_PAGE_REQUEST";
export const CINEMA_DETAILS_SUCCESS = "movieDetailsReducer/CINEMA_DETAILS_PAGE_SUCCESS";
export const CINEMA_DETAILS_FAILED = "movieDetailsReducer/CINEMA_DETAILS_PAGE_FAILED";